package com.polytech.dao;
// Generated 16 sept. 2014 15:04:06 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Diplome generated by hbm2java
 */
@Entity
@Table(name="diplome"
    ,schema="appschema"
)
public class Diplome  implements java.io.Serializable {


     private int id;
     private String typediplome;
     private Integer anneediplome;
     private String libelle;
     private Set etudiants = new HashSet(0);

    public Diplome() {
    }

	
    public Diplome(int id) {
        this.id = id;
    }
    public Diplome(int id, String typediplome, Integer anneediplome, String libelle, Set etudiants) {
       this.id = id;
       this.typediplome = typediplome;
       this.anneediplome = anneediplome;
       this.libelle = libelle;
       this.etudiants = etudiants;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="typediplome")
    public String getTypediplome() {
        return this.typediplome;
    }
    
    public void setTypediplome(String typediplome) {
        this.typediplome = typediplome;
    }

    
    @Column(name="anneediplome")
    public Integer getAnneediplome() {
        return this.anneediplome;
    }
    
    public void setAnneediplome(Integer anneediplome) {
        this.anneediplome = anneediplome;
    }

    
    @Column(name="libelle")
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="etudiantdiplome", schema="appschema", joinColumns = { 
        @JoinColumn(name="dipid", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="etuid", nullable=false, updatable=false) })
    public Set getEtudiants() {
        return this.etudiants;
    }
    
    public void setEtudiants(Set etudiants) {
        this.etudiants = etudiants;
    }




}


