package com.polytech.dao;
// Generated 22 sept. 2014 11:47:31 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Entretien generated by hbm2java
 */
public class Entretien  implements java.io.Serializable {


     private int id;
     private Planning planning;
     private Entreprise entreprise;
     private Etudiant etudiant;
     private Integer priorite;
     private Date horaire;
     private Integer salleid;
     private Date duree;

    public Entretien() {
    }

	
    public Entretien(int id) {
        this.id = id;
    }
    public Entretien(int id, Planning planning, Entreprise entreprise, Etudiant etudiant, Integer priorite, Date horaire, Integer salleid, Date duree) {
       this.id = id;
       this.planning = planning;
       this.entreprise = entreprise;
       this.etudiant = etudiant;
       this.priorite = priorite;
       this.horaire = horaire;
       this.salleid = salleid;
       this.duree = duree;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Planning getPlanning() {
        return this.planning;
    }
    
    public void setPlanning(Planning planning) {
        this.planning = planning;
    }
    public Entreprise getEntreprise() {
        return this.entreprise;
    }
    
    public void setEntreprise(Entreprise entreprise) {
        this.entreprise = entreprise;
    }
    public Etudiant getEtudiant() {
        return this.etudiant;
    }
    
    public void setEtudiant(Etudiant etudiant) {
        this.etudiant = etudiant;
    }
    public Integer getPriorite() {
        return this.priorite;
    }
    
    public void setPriorite(Integer priorite) {
        this.priorite = priorite;
    }
    public Date getHoraire() {
        return this.horaire;
    }
    
    public void setHoraire(Date horaire) {
        this.horaire = horaire;
    }
    public Integer getSalleid() {
        return this.salleid;
    }
    
    public void setSalleid(Integer salleid) {
        this.salleid = salleid;
    }
    public Date getDuree() {
        return this.duree;
    }
    
    public void setDuree(Date duree) {
        this.duree = duree;
    }




}


