package com.polytech.dao;
// Generated 16 sept. 2014 15:04:06 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Entretien generated by hbm2java
 */
@Entity
@Table(name="entretien"
    ,schema="appschema"
    , uniqueConstraints = @UniqueConstraint(columnNames={"etuid", "entid", "evtid"}) 
)
public class Entretien  implements java.io.Serializable {


     private int id;
     private Evenement evenement;
     private Entreprise entreprise;
     private Salle salle;
     private Etudiant etudiant;
     private Integer priorite;
     private Date horaire;

    public Entretien() {
    }

	
    public Entretien(int id) {
        this.id = id;
    }
    public Entretien(int id, Evenement evenement, Entreprise entreprise, Salle salle, Etudiant etudiant, Integer priorite, Date horaire) {
       this.id = id;
       this.evenement = evenement;
       this.entreprise = entreprise;
       this.salle = salle;
       this.etudiant = etudiant;
       this.priorite = priorite;
       this.horaire = horaire;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="evtid")
    public Evenement getEvenement() {
        return this.evenement;
    }
    
    public void setEvenement(Evenement evenement) {
        this.evenement = evenement;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="entid")
    public Entreprise getEntreprise() {
        return this.entreprise;
    }
    
    public void setEntreprise(Entreprise entreprise) {
        this.entreprise = entreprise;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="salleid")
    public Salle getSalle() {
        return this.salle;
    }
    
    public void setSalle(Salle salle) {
        this.salle = salle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="etuid")
    public Etudiant getEtudiant() {
        return this.etudiant;
    }
    
    public void setEtudiant(Etudiant etudiant) {
        this.etudiant = etudiant;
    }

    
    @Column(name="priorite")
    public Integer getPriorite() {
        return this.priorite;
    }
    
    public void setPriorite(Integer priorite) {
        this.priorite = priorite;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="horaire", length=15)
    public Date getHoraire() {
        return this.horaire;
    }
    
    public void setHoraire(Date horaire) {
        this.horaire = horaire;
    }




}


