package com.polytech.dao;
// Generated 23 sept. 2014 09:06:02 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Entreprisepresence generated by hbm2java
 */

public class Entreprisepresence implements java.io.Serializable {

    private int id;

    @JsonIgnore
    private int entid;
    private Entreprise entreprise;

    @JsonIgnore
    private int evtid;
    private Evenement evenement;
    private Personnecontact personnecontact;
    private Salle salle;
    private Boolean presence;
    private Date dureeentretien;

    private Set voeuxEntreprise = new HashSet();

    public Entreprisepresence() {
    }

    public Entreprisepresence(int id) {
        this.id = id;
    }

    public Entreprisepresence(int id, int entid, Entreprise entreprise, int evtid, Evenement evenement, Personnecontact personnecontact, Salle salle, Boolean presence, Date dureeentretien, Set voeuxEntreprise) {
        this.id = id;
        this.entid = entid;
        this.entreprise = entreprise;
        this.evtid = evtid;
        this.evenement = evenement;
        this.personnecontact = personnecontact;
        this.salle = salle;
        this.presence = presence;
        this.dureeentretien = dureeentretien;
        this.voeuxEntreprise = voeuxEntreprise;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Entreprise getEntreprise() {
        return this.entreprise;
    }

    public void setEntreprise(Entreprise entreprise) {
        this.entreprise = entreprise;
    }

    public int getEntid() {
        return entid;
    }

    public void setEntid(int entid) {
        this.entid = entid;
    }

    public Evenement getEvenement() {
        return this.evenement;
    }

    public int getEvtid() {
        return evtid;
    }

    public void setEvtid(int evtid) {
        this.evtid = evtid;
    }

    public void setEvenement(Evenement evenement) {
        this.evenement = evenement;
    }

    public Personnecontact getPersonnecontact() {
        return this.personnecontact;
    }

    public void setPersonnecontact(Personnecontact personnecontact) {
        this.personnecontact = personnecontact;
    }

    public Salle getSalle() {
        return this.salle;
    }

    public void setSalle(Salle salle) {
        this.salle = salle;
    }

    public Boolean getPresence() {
        return presence;
    }

    public void setPresence(Boolean entreprisepresence) {
        this.presence = entreprisepresence;
    }

    public Date getDureeentretien() {
        return this.dureeentretien;
    }

    public void setDureeentretien(Date dureeentretien) {
        this.dureeentretien = dureeentretien;
    }

    public Set<VoeuxEntreprise> getVoeuxEntreprise() {
        return voeuxEntreprise;
    }

    public void setVoeuxEntreprise(Set<VoeuxEntreprise> voeuxEntreprise) {
        this.voeuxEntreprise = voeuxEntreprise;
    }
}
