package com.polytech.dao;
// Generated 16 sept. 2014 15:04:06 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Entreprisepresence generated by hbm2java
 */
@Entity
@Table(name="entreprisepresence"
    ,schema="appschema"
)
public class Entreprisepresence  implements java.io.Serializable {


     private int id;
     private Evenement evenement;
     private Personnecontact personnecontact;
     private Entreprise entreprise;
     private Salle salle;
     private Boolean entreprisepresence;
     private Date dureeentretien;

    public Entreprisepresence() {
    }

	
    public Entreprisepresence(int id) {
        this.id = id;
    }
    public Entreprisepresence(int id, Evenement evenement, Personnecontact personnecontact, Entreprise entreprise, Salle salle, Boolean entreprisepresence, Date dureeentretien) {
       this.id = id;
       this.evenement = evenement;
       this.personnecontact = personnecontact;
       this.entreprise = entreprise;
       this.salle = salle;
       this.entreprisepresence = entreprisepresence;
       this.dureeentretien = dureeentretien;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="evtid")
    public Evenement getEvenement() {
        return this.evenement;
    }
    
    public void setEvenement(Evenement evenement) {
        this.evenement = evenement;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="perid")
    public Personnecontact getPersonnecontact() {
        return this.personnecontact;
    }
    
    public void setPersonnecontact(Personnecontact personnecontact) {
        this.personnecontact = personnecontact;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="entid")
    public Entreprise getEntreprise() {
        return this.entreprise;
    }
    
    public void setEntreprise(Entreprise entreprise) {
        this.entreprise = entreprise;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="salleid")
    public Salle getSalle() {
        return this.salle;
    }
    
    public void setSalle(Salle salle) {
        this.salle = salle;
    }

    
    @Column(name="entreprisepresence")
    public Boolean getEntreprisepresence() {
        return this.entreprisepresence;
    }
    
    public void setEntreprisepresence(Boolean entreprisepresence) {
        this.entreprisepresence = entreprisepresence;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="dureeentretien", length=15)
    public Date getDureeentretien() {
        return this.dureeentretien;
    }
    
    public void setDureeentretien(Date dureeentretien) {
        this.dureeentretien = dureeentretien;
    }




}


