package com.polytech.dao;
// Generated 23 sept. 2014 09:06:02 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;

/**
 * Entreprise generated by hbm2java
 */
public class Entreprise implements java.io.Serializable {

    private int id;
    private String raison;
    private String naf;
    private String siret;
    private String effectif;
    private String organisme;
    private String adresse;
    private String adresse2;
    private String cp;
    private String ville;
    private String tel;
    private String anneeparticipforum;
    private Integer nbrapprenti;

    private Set offrealternances = new HashSet(0);
    @JsonBackReference("Ent_personnecontacts")
    private Set personnecontacts = new HashSet(0);

    public Entreprise() {
    }

    public Entreprise(int id) {
        this.id = id;
    }

    public Entreprise(int id, String raison, String naf, String siret, String effectif, String organisme, String adresse, String adresse2, String cp, String ville, String tel, String anneeparticipforum, Integer nbrapprenti, Set offrealternances, Set personnecontacts) {
        this.id = id;
        this.raison = raison;
        this.naf = naf;
        this.siret = siret;
        this.effectif = effectif;
        this.organisme = organisme;
        this.adresse = adresse;
        this.adresse2 = adresse2;
        this.cp = cp;
        this.ville = ville;
        this.tel = tel;
        this.anneeparticipforum = anneeparticipforum;
        this.nbrapprenti = nbrapprenti;
        this.offrealternances = offrealternances;
        this.personnecontacts = personnecontacts;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getRaison() {
        return this.raison;
    }

    public void setRaison(String raison) {
        this.raison = raison;
    }

    public String getNaf() {
        return this.naf;
    }

    public void setNaf(String naf) {
        this.naf = naf;
    }

    public String getSiret() {
        return this.siret;
    }

    public void setSiret(String siret) {
        this.siret = siret;
    }

    public String getEffectif() {
        return this.effectif;
    }

    public void setEffectif(String effectif) {
        this.effectif = effectif;
    }

    public String getOrganisme() {
        return this.organisme;
    }

    public void setOrganisme(String organisme) {
        this.organisme = organisme;
    }

    public String getAdresse() {
        return this.adresse;
    }

    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    public String getAdresse2() {
        return this.adresse2;
    }

    public void setAdresse2(String adresse2) {
        this.adresse2 = adresse2;
    }

    public String getCp() {
        return this.cp;
    }

    public void setCp(String cp) {
        this.cp = cp;
    }

    public String getVille() {
        return this.ville;
    }

    public void setVille(String ville) {
        this.ville = ville;
    }

    public String getTel() {
        return this.tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getAnneeparticipforum() {
        return this.anneeparticipforum;
    }

    public void setAnneeparticipforum(String anneeparticipforum) {
        this.anneeparticipforum = anneeparticipforum;
    }

    public Integer getNbrapprenti() {
        return this.nbrapprenti;
    }

    public void setNbrapprenti(Integer nbrapprenti) {
        this.nbrapprenti = nbrapprenti;
    }

    public Set getOffrealternances() {
        return this.offrealternances;
    }

    public void setOffrealternances(Set offrealternances) {
        this.offrealternances = offrealternances;
    }

    public Set getPersonnecontacts() {
        return this.personnecontacts;
    }

    public void setPersonnecontacts(Set personnecontacts) {
        this.personnecontacts = personnecontacts;
    }

}
