package com.polytech.dao;
// Generated 23 sept. 2014 09:06:02 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.polytech.json.deserialization.JsonDateDeserializer_hour;
import com.polytech.json.deserialization.JsonHourDeserializer;
import com.polytech.json.serialization.JsonDateSerializer_hour;
import com.polytech.json.serialization.JsonHourSerializer;
import org.joda.time.DateTime;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Entreprisepresence generated by hbm2java
 */

public class Entreprisepresence implements java.io.Serializable {

    private int id;

    private Entreprise entreprise;

    @JsonIgnore
    private Evenement evenement;
    private Salle salle;
    private Boolean presence;
    private Date dureeentretien;

    private Set voeuxEntreprise = new HashSet();

    public Entreprisepresence() {

    }

    public Entreprisepresence(int id) {
        this.id = id;
    }

    public Entreprisepresence(int id, Entreprise entreprise, Evenement evenement, Salle salle, Boolean presence, Date dureeentretien, Set voeuxEntreprise) {
        this.id = id;
        this.entreprise = entreprise;
        this.evenement = evenement;
        this.salle = salle;
        this.presence = presence;
        this.dureeentretien = dureeentretien;
        this.voeuxEntreprise = voeuxEntreprise;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Entreprise getEntreprise() {
        return this.entreprise;
    }

    public void setEntreprise(Entreprise entreprise) {
        this.entreprise = entreprise;
    }

    public Salle getSalle() {
        return this.salle;
    }

    public void setSalle(Salle salle) {
        this.salle = salle;
    }

    public Boolean getPresence() {
        return presence;
    }

    public void setPresence(Boolean entreprisepresence) {
        this.presence = entreprisepresence;
    }

    @JsonSerialize(using = JsonDateSerializer_hour.class)
    public Date getDureeentretien() {
        return this.dureeentretien;
    }

    @JsonDeserialize(using = JsonDateDeserializer_hour.class)
    public void setDureeentretien(Date dureeentretien) {
        this.dureeentretien = dureeentretien;
    }

    public Set<VoeuxEntreprise> getVoeuxEntreprise() {
        return voeuxEntreprise;
    }

    public void setVoeuxEntreprise(Set<VoeuxEntreprise> voeuxEntreprise) {
        this.voeuxEntreprise = voeuxEntreprise;
    }

    public Evenement getEvenement() {
        return evenement;
    }

    public void setEvenement(Evenement evenement) {
        this.evenement = evenement;
    }

//    @Override
//    public boolean equals(Object obj) {
//        Entreprisepresence e = (Entreprisepresence) obj;
//        return this.getId() == e.getId();
//    }

}
