package com.polytech.dao;
// Generated 23 sept. 2014 09:06:02 by Hibernate Tools 4.3.1



/**
 * EvenementsalleId generated by hbm2java
 */
public class EtudiantevenementId implements java.io.Serializable {


     private int evtid;
     private int etuid;

    public EtudiantevenementId() {
    }

    public EtudiantevenementId(int evtid, int etuid) {
        this.evtid = evtid;
        this.etuid = etuid;
    }

    public int getEvtid() {
        return evtid;
    }

    public void setEvtid(int evtid) {
        this.evtid = evtid;
    }

    public int getEtuid() {
        return etuid;
    }

    public void setEtuid(int etuid) {
        this.etuid = etuid;
    }

    public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EtudiantevenementId) ) return false;
		 EtudiantevenementId castOther = (EtudiantevenementId) other;
         
		 return (this.getEvtid()==castOther.getEvtid()) && (this.getEtuid()==castOther.getEtuid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEvtid();
         result = 37 * result + this.getEtuid();
         return result;
   }   


}


