package com.polytech.dao;
// Generated 23 sept. 2014 09:06:02 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Etudiant generated by hbm2java
 */
public class Etudiant  implements java.io.Serializable {


     private int id;
     private Integer candidid;
     private String civilite;
     private String nom;
     private String prenom;
     private Date datenaissance;
     private String adresse;
     private String cp;
     private String ville;
     private String pays;
     private String telfixe;
     private String telportable;
     private String email;
     private Integer bacannee;
     private String bacmention;
     private String bactype;
     private String bacoption;
     private String formation;
     private String etab;
     private String etabcp;
     private String etabville;
     private String nivanglais;
     private String classement;
     private String cv;
     private String lettremotiv;
     private String avispoursuite;
     private String avisperso;
     private String rmq;
     private String candidstatut;
     private Set diplomes = new HashSet(0);
     private Set evenements = new HashSet(0);
     private Set voeuxEtudiants = new HashSet(0);
     private Set entretiens = new HashSet(0);
     private Set voeuxEntreprises = new HashSet(0);

    public Etudiant() {
    }

	
    public Etudiant(int id) {
        this.id = id;
    }
    public Etudiant(int id, Integer candidid, String civilite, String nom, String prenom, Date datenaissance, String adresse, String cp, String ville, String pays, String telfixe, String telportable, String email, Integer bacannee, String bacmention, String bactype, String bacoption, String formation, String etab, String etabcp, String etabville, String nivanglais, String classement, String cv, String lettremotiv, String avispoursuite, String avisperso, String rmq, String candidstatut, Set diplomes, Set evenements, Set voeuxEtudiants, Set entretiens, Set voeuxEntreprises) {
       this.id = id;
       this.candidid = candidid;
       this.civilite = civilite;
       this.nom = nom;
       this.prenom = prenom;
       this.datenaissance = datenaissance;
       this.adresse = adresse;
       this.cp = cp;
       this.ville = ville;
       this.pays = pays;
       this.telfixe = telfixe;
       this.telportable = telportable;
       this.email = email;
       this.bacannee = bacannee;
       this.bacmention = bacmention;
       this.bactype = bactype;
       this.bacoption = bacoption;
       this.formation = formation;
       this.etab = etab;
       this.etabcp = etabcp;
       this.etabville = etabville;
       this.nivanglais = nivanglais;
       this.classement = classement;
       this.cv = cv;
       this.lettremotiv = lettremotiv;
       this.avispoursuite = avispoursuite;
       this.avisperso = avisperso;
       this.rmq = rmq;
       this.candidstatut = candidstatut;
       this.diplomes = diplomes;
       this.evenements = evenements;
       this.voeuxEtudiants = voeuxEtudiants;
       this.entretiens = entretiens;
       this.voeuxEntreprises = voeuxEntreprises;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getCandidid() {
        return this.candidid;
    }
    
    public void setCandidid(Integer candidid) {
        this.candidid = candidid;
    }
    public String getCivilite() {
        return this.civilite;
    }
    
    public void setCivilite(String civilite) {
        this.civilite = civilite;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public Date getDatenaissance() {
        return this.datenaissance;
    }
    
    public void setDatenaissance(Date datenaissance) {
        this.datenaissance = datenaissance;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public String getPays() {
        return this.pays;
    }
    
    public void setPays(String pays) {
        this.pays = pays;
    }
    public String getTelfixe() {
        return this.telfixe;
    }
    
    public void setTelfixe(String telfixe) {
        this.telfixe = telfixe;
    }
    public String getTelportable() {
        return this.telportable;
    }
    
    public void setTelportable(String telportable) {
        this.telportable = telportable;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getBacannee() {
        return this.bacannee;
    }
    
    public void setBacannee(Integer bacannee) {
        this.bacannee = bacannee;
    }
    public String getBacmention() {
        return this.bacmention;
    }
    
    public void setBacmention(String bacmention) {
        this.bacmention = bacmention;
    }
    public String getBactype() {
        return this.bactype;
    }
    
    public void setBactype(String bactype) {
        this.bactype = bactype;
    }
    public String getBacoption() {
        return this.bacoption;
    }
    
    public void setBacoption(String bacoption) {
        this.bacoption = bacoption;
    }
    public String getFormation() {
        return this.formation;
    }
    
    public void setFormation(String formation) {
        this.formation = formation;
    }
    public String getEtab() {
        return this.etab;
    }
    
    public void setEtab(String etab) {
        this.etab = etab;
    }
    public String getEtabcp() {
        return this.etabcp;
    }
    
    public void setEtabcp(String etabcp) {
        this.etabcp = etabcp;
    }
    public String getEtabville() {
        return this.etabville;
    }
    
    public void setEtabville(String etabville) {
        this.etabville = etabville;
    }
    public String getNivanglais() {
        return this.nivanglais;
    }
    
    public void setNivanglais(String nivanglais) {
        this.nivanglais = nivanglais;
    }
    public String getClassement() {
        return this.classement;
    }
    
    public void setClassement(String classement) {
        this.classement = classement;
    }
    public String getCv() {
        return this.cv;
    }
    
    public void setCv(String cv) {
        this.cv = cv;
    }
    public String getLettremotiv() {
        return this.lettremotiv;
    }
    
    public void setLettremotiv(String lettremotiv) {
        this.lettremotiv = lettremotiv;
    }
    public String getAvispoursuite() {
        return this.avispoursuite;
    }
    
    public void setAvispoursuite(String avispoursuite) {
        this.avispoursuite = avispoursuite;
    }
    public String getAvisperso() {
        return this.avisperso;
    }
    
    public void setAvisperso(String avisperso) {
        this.avisperso = avisperso;
    }
    public String getRmq() {
        return this.rmq;
    }
    
    public void setRmq(String rmq) {
        this.rmq = rmq;
    }
    public String getCandidstatut() {
        return this.candidstatut;
    }
    
    public void setCandidstatut(String candidstatut) {
        this.candidstatut = candidstatut;
    }
    public Set getDiplomes() {
        return this.diplomes;
    }
    
    public void setDiplomes(Set diplomes) {
        this.diplomes = diplomes;
    }
    public Set getEvenements() {
        return this.evenements;
    }
    
    public void setEvenements(Set evenements) {
        this.evenements = evenements;
    }
    public Set getVoeuxEtudiants() {
        return this.voeuxEtudiants;
    }
    
    public void setVoeuxEtudiants(Set voeuxEtudiants) {
        this.voeuxEtudiants = voeuxEtudiants;
    }
    public Set getEntretiens() {
        return this.entretiens;
    }
    
    public void setEntretiens(Set entretiens) {
        this.entretiens = entretiens;
    }
    public Set getVoeuxEntreprises() {
        return this.voeuxEntreprises;
    }
    
    public void setVoeuxEntreprises(Set voeuxEntreprises) {
        this.voeuxEntreprises = voeuxEntreprises;
    }




}


