package com.polytech.dao;
// Generated 23 sept. 2014 09:06:02 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Evenementsalle generated by hbm2java
 */
public class Evenementsalle implements java.io.Serializable {


    private int id;

    @JsonIgnore
    private Evenement evenement;

    private Salle salle;
    public Evenementsalle() {
    }

    public Evenementsalle(int id, Evenement evenement, Salle salle) {
        this.id = id;
        this.evenement = evenement;
        this.salle = salle;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Evenement getEvenement() {
        return this.evenement;
    }

    public void setEvenement(Evenement evenement) {
        this.evenement = evenement;
    }

    public Salle getSalle() {
        return this.salle;
    }

    public void setSalle(Salle salle) {
        this.salle = salle;
    }


}


