package com.polytech.dao;
// Generated 22 sept. 2014 11:47:31 by Hibernate Tools 3.6.0



/**
 * Evenementsalle generated by hbm2java
 */
public class Evenementsalle  implements java.io.Serializable {


     private EvenementsalleId id;
     private Evenement evenement;
     private Salle salle;

    public Evenementsalle() {
    }

    public Evenementsalle(EvenementsalleId id, Evenement evenement, Salle salle) {
       this.id = id;
       this.evenement = evenement;
       this.salle = salle;
    }
   
    public EvenementsalleId getId() {
        return this.id;
    }
    
    public void setId(EvenementsalleId id) {
        this.id = id;
    }
    public Evenement getEvenement() {
        return this.evenement;
    }
    
    public void setEvenement(Evenement evenement) {
        this.evenement = evenement;
    }
    public Salle getSalle() {
        return this.salle;
    }
    
    public void setSalle(Salle salle) {
        this.salle = salle;
    }




}


