package com.polytech.dao;
// Generated 16 sept. 2014 15:04:06 by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Evenementsalle generated by hbm2java
 */
@Entity
@Table(name="evenementsalle"
    ,schema="appschema"
)
public class Evenementsalle  implements java.io.Serializable {


     private EvenementsalleId id;
     private Evenement evenement;
     private Salle salle;

    public Evenementsalle() {
    }

    public Evenementsalle(EvenementsalleId id, Evenement evenement, Salle salle) {
       this.id = id;
       this.evenement = evenement;
       this.salle = salle;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="evtid", column=@Column(name="evtid", nullable=false) ), 
        @AttributeOverride(name="salleid", column=@Column(name="salleid", nullable=false) ) } )
    public EvenementsalleId getId() {
        return this.id;
    }
    
    public void setId(EvenementsalleId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="evtid", nullable=false, insertable=false, updatable=false)
    public Evenement getEvenement() {
        return this.evenement;
    }
    
    public void setEvenement(Evenement evenement) {
        this.evenement = evenement;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="evtid", nullable=false, insertable=false, updatable=false)
    public Salle getSalle() {
        return this.salle;
    }
    
    public void setSalle(Salle salle) {
        this.salle = salle;
    }




}


