package com.polytech.dao;
// Generated 16 sept. 2014 15:04:06 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EvenementsalleId generated by hbm2java
 */
@Embeddable
public class EvenementsalleId  implements java.io.Serializable {


     private int evtid;
     private int salleid;

    public EvenementsalleId() {
    }

    public EvenementsalleId(int evtid, int salleid) {
       this.evtid = evtid;
       this.salleid = salleid;
    }
   


    @Column(name="evtid", nullable=false)
    public int getEvtid() {
        return this.evtid;
    }
    
    public void setEvtid(int evtid) {
        this.evtid = evtid;
    }


    @Column(name="salleid", nullable=false)
    public int getSalleid() {
        return this.salleid;
    }
    
    public void setSalleid(int salleid) {
        this.salleid = salleid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EvenementsalleId) ) return false;
		 EvenementsalleId castOther = ( EvenementsalleId ) other; 
         
		 return (this.getEvtid()==castOther.getEvtid())
 && (this.getSalleid()==castOther.getSalleid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEvtid();
         result = 37 * result + this.getSalleid();
         return result;
   }   


}


