package com.polytech.dao;
// Generated 22 sept. 2014 11:47:31 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Evenement generated by hbm2java
 */
public class Evenement  implements java.io.Serializable {


     private int id;
     private String typeevt;
     private Date dateevt;
     private String duree;
     private Date heuredebut;
     private Date heurefin;
     private String description;
     private Set evenementsalles = new HashSet(0);
     private Set evenementsalles_1 = new HashSet(0);
     private Set entreprisepresences = new HashSet(0);
     private Set plannings = new HashSet(0);
     private Set voeuxEtudiants = new HashSet(0);
     private Set etudiants = new HashSet(0);
     private Set voeuxEntreprises = new HashSet(0);

    public Evenement() {
    }

	
    public Evenement(int id) {
        this.id = id;
    }
    public Evenement(int id, String typeevt, Date dateevt, String duree, Date heuredebut, Date heurefin, String description, Set evenementsalles, Set evenementsalles_1, Set entreprisepresences, Set plannings, Set voeuxEtudiants, Set etudiants, Set voeuxEntreprises) {
       this.id = id;
       this.typeevt = typeevt;
       this.dateevt = dateevt;
       this.duree = duree;
       this.heuredebut = heuredebut;
       this.heurefin = heurefin;
       this.description = description;
       this.evenementsalles = evenementsalles;
       this.evenementsalles_1 = evenementsalles_1;
       this.entreprisepresences = entreprisepresences;
       this.plannings = plannings;
       this.voeuxEtudiants = voeuxEtudiants;
       this.etudiants = etudiants;
       this.voeuxEntreprises = voeuxEntreprises;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTypeevt() {
        return this.typeevt;
    }
    
    public void setTypeevt(String typeevt) {
        this.typeevt = typeevt;
    }
    public Date getDateevt() {
        return this.dateevt;
    }
    
    public void setDateevt(Date dateevt) {
        this.dateevt = dateevt;
    }
    public String getDuree() {
        return this.duree;
    }
    
    public void setDuree(String duree) {
        this.duree = duree;
    }
    public Date getHeuredebut() {
        return this.heuredebut;
    }
    
    public void setHeuredebut(Date heuredebut) {
        this.heuredebut = heuredebut;
    }
    public Date getHeurefin() {
        return this.heurefin;
    }
    
    public void setHeurefin(Date heurefin) {
        this.heurefin = heurefin;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getEvenementsalles() {
        return this.evenementsalles;
    }
    
    public void setEvenementsalles(Set evenementsalles) {
        this.evenementsalles = evenementsalles;
    }
    public Set getEvenementsalles_1() {
        return this.evenementsalles_1;
    }
    
    public void setEvenementsalles_1(Set evenementsalles_1) {
        this.evenementsalles_1 = evenementsalles_1;
    }
    public Set getEntreprisepresences() {
        return this.entreprisepresences;
    }
    
    public void setEntreprisepresences(Set entreprisepresences) {
        this.entreprisepresences = entreprisepresences;
    }
    public Set getPlannings() {
        return this.plannings;
    }
    
    public void setPlannings(Set plannings) {
        this.plannings = plannings;
    }
    public Set getVoeuxEtudiants() {
        return this.voeuxEtudiants;
    }
    
    public void setVoeuxEtudiants(Set voeuxEtudiants) {
        this.voeuxEtudiants = voeuxEtudiants;
    }
    public Set getEtudiants() {
        return this.etudiants;
    }
    
    public void setEtudiants(Set etudiants) {
        this.etudiants = etudiants;
    }
    public Set getVoeuxEntreprises() {
        return this.voeuxEntreprises;
    }
    
    public void setVoeuxEntreprises(Set voeuxEntreprises) {
        this.voeuxEntreprises = voeuxEntreprises;
    }




}


