package com.polytech.dao;
// Generated 23 sept. 2014 09:06:02 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Evenement generated by hbm2java
 */
public class Evenement implements java.io.Serializable {

    private int id;
    private String typeevt;
    private Date dateevt;
    private String duree;
    private Date heuredebut;
    private Date heurefin;
    private String description;
    @JsonBackReference("Evt_evenementsalles")
    private Set evenementsalles = new HashSet(0);

    private Set evenementsalles_1 = new HashSet(0);

    @JsonBackReference("Evt_entreprisepresences")
    private Set entreprisepresences = new HashSet(0);
    @JsonBackReference("Evt_plannings")
    private Set plannings = new HashSet(0);
    //@JsonManagedReference("Etu_evenements")
    private Set etudiantpresents = new HashSet(0);

    public Evenement() {
    }

    public Evenement(int id) {
        this.id = id;
    }

    public Evenement(int id, String typeevt, Date dateevt, String duree, Date heuredebut, Date heurefin, String description, Set evenementsalles, Set evenementsalles_1, Set entreprisepresences, Set plannings, Set voeuxEtudiants, Set etudiantpresents, Set voeuxEntreprises) {
        this.id = id;
        this.typeevt = typeevt;
        this.dateevt = dateevt;
        this.duree = duree;
        this.heuredebut = heuredebut;
        this.heurefin = heurefin;
        this.description = description;
        this.evenementsalles = evenementsalles;
        this.evenementsalles_1 = evenementsalles_1;
        this.entreprisepresences = entreprisepresences;
        this.plannings = plannings;
        this.etudiantpresents = etudiantpresents;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTypeevt() {
        return this.typeevt;
    }

    public void setTypeevt(String typeevt) {
        this.typeevt = typeevt;
    }

    @JsonSerialize(using = JsonDateSerializer.class)
    public Date getDateevt() {
        return this.dateevt;
    }

    @JsonDeserialize(using = JsonDateDeserializer.class)
    public void setDateevt(Date dateevt) {
        this.dateevt = dateevt;
    }

    public String getDuree() {
        return this.duree;
    }

    public void setDuree(String duree) {
        this.duree = duree;
    }

    @JsonSerialize(using = JsonDateSerializer_hour.class)
    public Date getHeuredebut() {
        return this.heuredebut;
    }
   @JsonDeserialize(using = JsonDateDeserializer_hour.class)
    public void setHeuredebut(Date heuredebut) {
        this.heuredebut = heuredebut;
    }

       @JsonSerialize(using = JsonDateSerializer_hour.class)
    public Date getHeurefin() {
        return this.heurefin;
    }
  @JsonDeserialize(using = JsonDateDeserializer_hour.class)
    public void setHeurefin(Date heurefin) {
        this.heurefin = heurefin;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set getEvenementsalles() {
        return this.evenementsalles;
    }

    public void setEvenementsalles(Set evenementsalles) {
        this.evenementsalles = evenementsalles;
    }

    public Set getEvenementsalles_1() {
        return this.evenementsalles_1;
    }

    public void setEvenementsalles_1(Set evenementsalles_1) {
        this.evenementsalles_1 = evenementsalles_1;
    }

    public Set getEntreprisepresences() {
        return this.entreprisepresences;
    }

    public void setEntreprisepresences(Set entreprisepresences) {
        this.entreprisepresences = entreprisepresences;
    }

    public Set getPlannings() {
        return this.plannings;
    }

    public void setPlannings(Set plannings) {
        this.plannings = plannings;
    }

    public Set getEtudiants() {
        return this.etudiantpresents;
    }

    public void setEtudiants(Set etudiants) {
        this.etudiantpresents = etudiants;
    }

}
