package com.polytech.dao;
// Generated 16 sept. 2014 15:04:06 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Offrealternance generated by hbm2java
 */
@Entity
@Table(name="offrealternance"
    ,schema="appschema"
)
public class Offrealternance  implements java.io.Serializable {


     private int id;
     private Entreprise entreprise;
     private String titre;
     private String url;

    public Offrealternance() {
    }

	
    public Offrealternance(int id) {
        this.id = id;
    }
    public Offrealternance(int id, Entreprise entreprise, String titre, String url) {
       this.id = id;
       this.entreprise = entreprise;
       this.titre = titre;
       this.url = url;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="entid")
    public Entreprise getEntreprise() {
        return this.entreprise;
    }
    
    public void setEntreprise(Entreprise entreprise) {
        this.entreprise = entreprise;
    }

    
    @Column(name="titre")
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }

    
    @Column(name="url")
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


