package com.polytech.dao;
// Generated 23 sept. 2014 09:06:02 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import java.util.HashSet;
import java.util.Set;

/**
 * Personnecontact generated by hbm2java
 */
public class Personnecontact implements java.io.Serializable {

    private int id;

    private Entreprise entreprise;
    private String civilite;
    private String nom;
    private String prenom;
    private String role;
    private String telfixe;
    private String telportable;
    private String email;

    public Personnecontact() {
    }

    public Personnecontact(int id) {
        this.id = id;
    }

    public Personnecontact(int id, Entreprise entreprise, String civilite, String nom, String prenom, String role, String telfixe, String telportable, String email) {
        this.id = id;
        this.entreprise = entreprise;
        this.civilite = civilite;
        this.nom = nom;
        this.prenom = prenom;
        this.role = role;
        this.telfixe = telfixe;
        this.telportable = telportable;
        this.email = email;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Entreprise getEntreprise() {
        return this.entreprise;
    }

    public void setEntreprise(Entreprise entreprise) {
        this.entreprise = entreprise;
    }

    public String getCivilite() {
        return this.civilite;
    }

    public void setCivilite(String civilite) {
        this.civilite = civilite;
    }

    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getPrenom() {
        return this.prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getTelfixe() {
        return this.telfixe;
    }

    public void setTelfixe(String telfixe) {
        this.telfixe = telfixe;
    }

    public String getTelportable() {
        return this.telportable;
    }

    public void setTelportable(String telportable) {
        this.telportable = telportable;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

}
