package com.polytech.dao;
// Generated 23 sept. 2014 09:06:02 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonBackReference;

import java.util.HashSet;
import java.util.Set;

/**
 * Salle generated by hbm2java
 */
public class Salle  implements java.io.Serializable {


     private int id;
     private String libelle;
     private String localisation;
     private Integer capacite;

    public Salle() {
    }

	
    public Salle(int id) {
        this.id = id;
    }
    
    public Salle(int id, String libelle, String localisation, Integer capacite) {
       this.id = id;
       this.libelle = libelle;
       this.localisation = localisation;
       this.capacite = capacite;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
    public String getLocalisation() {
        return this.localisation;
    }
    
    public void setLocalisation(String localisation) {
        this.localisation = localisation;
    }
    public Integer getCapacite() {
        return this.capacite;
    }
    
    public void setCapacite(Integer capacite) {
        this.capacite = capacite;
    }

}


