package com.polytech.dao;
// Generated 16 sept. 2014 15:04:06 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Salle generated by hbm2java
 */
@Entity
@Table(name="salle"
    ,schema="appschema"
)
public class Salle  implements java.io.Serializable {


     private int id;
     private String libelle;
     private String localisation;
     private Integer capacite;
     private Set entreprisepresences = new HashSet(0);
     private Set entretiens = new HashSet(0);
     private Set evenementsalles = new HashSet(0);

    public Salle() {
    }

	
    public Salle(int id) {
        this.id = id;
    }
    public Salle(int id, String libelle, String localisation, Integer capacite, Set entreprisepresences, Set entretiens, Set evenementsalles) {
       this.id = id;
       this.libelle = libelle;
       this.localisation = localisation;
       this.capacite = capacite;
       this.entreprisepresences = entreprisepresences;
       this.entretiens = entretiens;
       this.evenementsalles = evenementsalles;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="libelle")
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="localisation")
    public String getLocalisation() {
        return this.localisation;
    }
    
    public void setLocalisation(String localisation) {
        this.localisation = localisation;
    }

    
    @Column(name="capacite")
    public Integer getCapacite() {
        return this.capacite;
    }
    
    public void setCapacite(Integer capacite) {
        this.capacite = capacite;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="salle")
    public Set getEntreprisepresences() {
        return this.entreprisepresences;
    }
    
    public void setEntreprisepresences(Set entreprisepresences) {
        this.entreprisepresences = entreprisepresences;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="salle")
    public Set getEntretiens() {
        return this.entretiens;
    }
    
    public void setEntretiens(Set entretiens) {
        this.entretiens = entretiens;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="evenement")
    public Set getEvenementsalles() {
        return this.evenementsalles;
    }
    
    public void setEvenementsalles(Set evenementsalles) {
        this.evenementsalles = evenementsalles;
    }




}


