package com.polytech.dao;
// Generated 23 sept. 2014 09:06:02 by Hibernate Tools 4.3.1



/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur  implements java.io.Serializable {


     private int id;
     private String login;
     private String mdp;
     private Boolean admin;
     private Boolean lecture;
     private Boolean ecriture;

    public Utilisateur() {
    }

	
    public Utilisateur(int id) {
        this.id = id;
    }
    public Utilisateur(int id, String login, String mdp, Boolean admin, Boolean lecture, Boolean ecriture) {
       this.id = id;
       this.login = login;
       this.mdp = mdp;
       this.admin = admin;
       this.lecture = lecture;
       this.ecriture = ecriture;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getMdp() {
        return this.mdp;
    }
    
    public void setMdp(String mdp) {
        this.mdp = mdp;
    }
    public Boolean getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Boolean admin) {
        this.admin = admin;
    }
    public Boolean getLecture() {
        return this.lecture;
    }
    
    public void setLecture(Boolean lecture) {
        this.lecture = lecture;
    }
    public Boolean getEcriture() {
        return this.ecriture;
    }
    
    public void setEcriture(Boolean ecriture) {
        this.ecriture = ecriture;
    }




}


