package com.polytech.dao;
// Generated 16 sept. 2014 15:04:06 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name="utilisateur"
    ,schema="appschema"
)
public class Utilisateur  implements java.io.Serializable {


     private int id;
     private String login;
     private String mdp;
     private Boolean admin;
     private Boolean lecture;
     private Boolean ecriture;

    public Utilisateur() {
    }

	
    public Utilisateur(int id) {
        this.id = id;
    }
    public Utilisateur(int id, String login, String mdp, Boolean admin, Boolean lecture, Boolean ecriture) {
       this.id = id;
       this.login = login;
       this.mdp = mdp;
       this.admin = admin;
       this.lecture = lecture;
       this.ecriture = ecriture;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="login")
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="mdp")
    public String getMdp() {
        return this.mdp;
    }
    
    public void setMdp(String mdp) {
        this.mdp = mdp;
    }

    
    @Column(name="admin")
    public Boolean getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(Boolean admin) {
        this.admin = admin;
    }

    
    @Column(name="lecture")
    public Boolean getLecture() {
        return this.lecture;
    }
    
    public void setLecture(Boolean lecture) {
        this.lecture = lecture;
    }

    
    @Column(name="ecriture")
    public Boolean getEcriture() {
        return this.ecriture;
    }
    
    public void setEcriture(Boolean ecriture) {
        this.ecriture = ecriture;
    }




}


