package com.polytech.dao;
// Generated 23 sept. 2014 09:06:02 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * VoeuxEntreprise generated by hbm2java
 */
public class VoeuxEntreprise implements java.io.Serializable {

    private int id;

    private Entreprisepresence entreprisepresence;
    private Etudiantevenement etudiantevenement;
    private Evenement evenement;

    public VoeuxEntreprise() {
    }

    public VoeuxEntreprise(int id) {
        this.id = id;
    }

    public VoeuxEntreprise(int id, Entreprisepresence entreprisepresence, Etudiantevenement etudiantevenement, Evenement evenement) {
        this.id = id;
        this.entreprisepresence = entreprisepresence;
        this.etudiantevenement = etudiantevenement;
        this.evenement = evenement;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Entreprisepresence getEntreprisepresence() {
        return this.entreprisepresence;
    }

    public void setEntreprisepresence(Entreprisepresence entreprisepresence) {
        this.entreprisepresence = entreprisepresence;
    }

    public Etudiantevenement getEtudiantevenement() {
        return this.etudiantevenement;
    }

    public void setEtudiantevenement(Etudiantevenement etudiantevenement) {
        this.etudiantevenement = etudiantevenement;
    }

    public Evenement getEvenement() {
        return this.evenement;
    }

    public void setEvenement(Evenement evenement) {
        this.evenement = evenement;
    }

}
