package com.polytech.dao;
// Generated 22 sept. 2014 11:47:31 by Hibernate Tools 3.6.0



/**
 * VoeuxEtudiant generated by hbm2java
 */
public class VoeuxEtudiant  implements java.io.Serializable {


     private int id;
     private Evenement evenement;
     private Entreprise entreprise;
     private Etudiant etudiant;
     private Integer niveau;

    public VoeuxEtudiant() {
    }

	
    public VoeuxEtudiant(int id) {
        this.id = id;
    }
    public VoeuxEtudiant(int id, Evenement evenement, Entreprise entreprise, Etudiant etudiant, Integer niveau) {
       this.id = id;
       this.evenement = evenement;
       this.entreprise = entreprise;
       this.etudiant = etudiant;
       this.niveau = niveau;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Evenement getEvenement() {
        return this.evenement;
    }
    
    public void setEvenement(Evenement evenement) {
        this.evenement = evenement;
    }
    public Entreprise getEntreprise() {
        return this.entreprise;
    }
    
    public void setEntreprise(Entreprise entreprise) {
        this.entreprise = entreprise;
    }
    public Etudiant getEtudiant() {
        return this.etudiant;
    }
    
    public void setEtudiant(Etudiant etudiant) {
        this.etudiant = etudiant;
    }
    public Integer getNiveau() {
        return this.niveau;
    }
    
    public void setNiveau(Integer niveau) {
        this.niveau = niveau;
    }




}


