package com.polytech.dao;
// Generated 23 sept. 2014 09:06:02 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * VoeuxEtudiant generated by hbm2java
 */
public class VoeuxEtudiant implements java.io.Serializable {

    private int id;
    private Entreprisepresence entreprisepresence;

    @JsonIgnore
    private Etudiantevenement etudiantevenement;
    private Integer niveau;

    public VoeuxEtudiant() {
    }

    public VoeuxEtudiant(int id) {
        this.id = id;
    }

    public VoeuxEtudiant(int id, Entreprisepresence entreprisepresence, Etudiantevenement etudiantevenement, Evenement evenement, Integer niveau) {
        this.id = id;
        this.entreprisepresence = entreprisepresence;
        this.etudiantevenement = etudiantevenement;
        this.niveau = niveau;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Entreprisepresence getEntreprisepresence() {
        return this.entreprisepresence;
    }

    public void setEntreprisepresence(Entreprisepresence entreprisepresence) {
        this.entreprisepresence = entreprisepresence;
    }

    public Etudiantevenement getEtudiantevenement() {
        return this.etudiantevenement;
    }

    public void setEtudiantevenement(Etudiantevenement etudiantevenement) {
        this.etudiantevenement = etudiantevenement;
    }

    public Integer getNiveau() {
        return this.niveau;
    }

    public void setNiveau(Integer niveau) {
        this.niveau = niveau;
    }

}
